#57 About page rework to use yml
gdidayton/gdidayton.com pull request #85
Opened 2017-10-30 02:21 UTC by spiraldancer

Updated about page to use yml/jekyll. There are two sections: leadership and staff. Also included a section to build the social links/icons. This will need updated with the correct hrefs and email address for the bios. It currently builds Sara's social as the page does now.

2018-01-15 18:08 UTC, kcjonesevans commented
Can you update based on the conflicts?

2018-01-15 23:06 UTC, spiraldancer commented
working on it now

2018-03-10 00:41 UTC, k80bowman requested changes
It's looking really nice, thanks for making all of these changes. I do have a couple of requests, though, before I can merge this in. Thanks again!

2018-03-10 00:41 UTC, k80bowman commented on _data/about_bios.yml
> +       inconclass: fa fa-envelope
could we change this to `iconclass`? I realize there are a lot of them, but I'd rather the name not be confusing. Thanks!

2018-03-10 00:41 UTC, k80bowman commented on _site/about/index.html
> -    </script>
Thanks for moving all of these to the bottom :)

2018-03-10 00:41 UTC, k80bowman commented on _site/css/application.css
> +
This is nice!

2018-03-10 00:41 UTC, k80bowman commented on _site/css/application.css
> +    div.social_links i:hover {
this hover effect is working a little strangely and I'm not sure it's applied to the correct element. The yellow background color hover gets applied when you hover just outside the icon like this:
![image](https://user-images.githubusercontent.com/12739849/37235809-e6f85c46-23cf-11e8-918a-fedfb1dcde61.png)

But the icon color doesn't change to white until you actually hover on the icon.

2018-03-10 00:41 UTC, k80bowman commented on about.html
> +      {% for currBio in site.data.about_bios.staff %}
Somehow Kevin's bio is being labeled "profile-left", which is why I think we're seeing this:
![image](https://user-images.githubusercontent.com/12739849/37235998-950ca462-23d1-11e8-9f06-f193089a71fa.png)

2018-05-23 01:50 UTC, k80bowman approved these changes

2018-05-29 01:11 UTC, k80bowman commented
These changes were merged using a different branch.

2018-05-29 01:11 UTC, closed without merging